spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: keimar.ok@gmail.com
    password: ypkwebcacewjoyqo
    port: '587'
  application:
    name: notification-service


springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    enabled: 'true'
    path: /api-docs


server:
  port: '9091'
